### ISSUE TITLE
yarpdataplayer-gtk compile failure without opencv

### ISSUE THREAD

**Issue by paulfitz** [robotology/yarp#388]
yarpdataplayer-gtk tries and fails to compile if opencv is not present

```
[ 86%] Building CXX object src/yarpdataplayer-gtk/CMakeFiles/yarpdataplayer-gtk.dir/src/main.cpp.o
In file included from /root/yarp2/src/yarpdataplayer-gtk/include/utils.h:32:0,
                 from /root/yarp2/src/yarpdataplayer-gtk/include/main_window.h:26,
                 from /root/yarp2/src/yarpdataplayer-gtk/src/main.cpp:27:
/root/yarp2/src/yarpdataplayer-gtk/include/worker.h:22:16: fatal error: cv.h: No such file or directory
compilation terminated.
```

**Comment by vtikha** [comment]
The latest changes seem to have broken the compilation switch (cmake) for the yarpdataplayer. I have both opencv and QT5 installed and yarpdataplayer is not being included in the yarp project. This has been noted on OS X and on Windows.

**Comment by vtikha** [comment]
Shouldn't OPENCV be written as: OpenCV?

**Comment by drdanz** [comment]
@vtikha Can you please confirm that this is fixed now?

**Comment by vtikha** [comment]
No it is not fixed! again...It seems that YARP_USE_OPENCV and subsequently YARP_HAS_OPENCV are not being set properly.

**Comment by vtikha** [comment]
e.g: if I put OpenCV_FOUND instead of YARP_HAS_OPENCV it works, but obviously this is not a proper way, it was just to try it out and confirm the above issue.

**Comment by drdanz** [comment]
Can you check if YARP_USE_OPENCV is enabled in your CMake cache?

**Comment by drdanz** [comment]
@vtikha Sorry, I looked again and everything seems good to me now, let me know when you have some time and we can investigate it on your computer...
Anyway, please ensure that ``YARP_USE_OPENCV`` is enabled, this is a flag that disables OpenCV (and therefore all packages that depend on it), even if it was found by CMake.

**Comment by pattacini** [comment]
Anyway, I've got the same problem on Windows.
Cannot find `YARP_USE_OPENCV` within cmake flags though, neither under advanced ones...

**Comment by drdanz** [comment]
@vtikha This time should be fixed for real :smile: 
Can you please confirm?

**Comment by pattacini** [comment]
it works on Windows.

**Comment by vtikha** [comment]
I confirm it now works for real!
